# Generated by Django 3.2.4 on 2021-09-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvpsite', '0002_remove_profile_name_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(null=True, upload_to='', verbose_name='Profile Picture: '),
        ),
    ]
