# Generated by Django 3.2.4 on 2021-09-12 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvpsite', '0003_alter_profile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_of_ratings',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='courierad',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Still accepting offers'), (1, 'A deal is in progress'), (2, 'A deal is completed'), (3, 'The courier has departed'), (4, 'The courier has arrived'), (5, 'Cancelled'), (8, 'Rated')], default=0),
        ),
        migrations.AlterField(
            model_name='packagead',
            name='receiver_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packagead_receive_a', to='mvpsite.address'),
        ),
        migrations.AlterField(
            model_name='packagead',
            name='sender_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packagead_send_a', to='mvpsite.address'),
        ),
        migrations.AlterField(
            model_name='packagead',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Still accepting offers'), (1, 'A deal is in progress'), (2, 'A deal is completed'), (3, 'The package has been dropped off'), (4, 'The package is with the courier'), (5, 'The courier has delivered the package'), (6, 'The package has been received'), (8, 'Cancelled'), (8, 'Rated')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Profile Picture: '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=2.5),
        ),
    ]
